config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'login' => 'sessions#new'
  post 'login' => "sessions#create"
  delete 'logout' => "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root 'orders#index'
    resources :orders
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  validates :email, presence: true, uniqueness: true

  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_details

  enum status: {created: 0, confirming: 1, sending: 2, done: 3, canceled: 4 }

  delegate :email, to: :user, prefix: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :product_form_db, class_name: "Product", foreign_key: "product_id"

  def product
    @product ||= Product.new.tap do |product|
      if product_raw_data
        saved_hash = JSON.parse(product_raw_data)
        product.attributes = saved_hash
        product.id = saved_hash['id']
      end
      product.readonly!
    end
  end

  def product=(product)
    product_raw_data = product.to_json
  end

  def amount
    unit_price * quanlity
  end
end

app/models/order_log.rb
class OrderLog < ApplicationRecord
  belongs_to :admin_user
  belongs_to :order

  def messages
    JSON.parse(message_raw_data.presence || "{}")
  end

end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true

  has_many :orders
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
  include SessionsHelper
  layout 'admin'
  protect_from_forgery with: :exception
  before_action :logged_in?

  private

  def logged_in?
    return redirect_to login_path unless current_admin_user
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :set_breadcrum

  # GET /orders
  def index
    @orders = SearchServices::Order.call(search_params)
  end

  # GET /orders/1
  def show
    @bcrum_detail = ["Order", "detail", @order.id]
  end

  # GET /orders/1/edit
  def edit
    @bcrum_detail = ["Order", "edit", @order.id]
  end

  # PATCH/PUT /orders/1
  def update
    o_status = @order.status
    if @order.update(order_params)
      LogServices::OrderStatus.call(current_admin_user, order: @order, o_status: o_status)
      OrdersMailer.change_status(@order).deliver_now!
      redirect_to admin_order_path(@order), notice: "Order was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def set_order
      @order = Order.find(params[:id]).decorate
    end

    def order_params
      params.require(:order).permit(:status)
    end

    def search_params
      s_params = params[:search]
      s_params = s_params.present? ? s_params.to_unsafe_h : {}
      s_params.merge!(page: params['page']) if params['page'].present?
      s_params
    end

    def set_breadcrum
      @bcrum_title = "Order"
      @bcrum_detail = ["Order"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  before_action :current_admin_user_present, only: %w[new create]


  def new; end

  def create
    user = AdminUser.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login success"
      log_in user
      redirect_back fallback_location: admin_root_path
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = "You are logged out"
    redirect_to login_path
  end

  private

  def current_admin_user_present
    return redirect_to admin_root_path if current_admin_user.present?
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def generate_breadcrum(title = '', bcrum_detail = [])
    lst = []
    lst << "<h1 class='mt-4'>#{title.capitalize}</h1>" if title.present?
    if bcrum_detail.is_a?(Array) && bcrum_detail.present?
      lst << "<ol class='breadcrumb mb-4'>"
      bcrum_detail_size = bcrum_detail.size - 1
      bcrum_detail.each_with_index do |breadcrumb, idx|
        active = idx == bcrum_detail_size ? 'active' : ''
        lst << "<li class='breadcrumb-item #{active}'>#{breadcrumb.to_s.capitalize}</li>"
      end
      lst << "</ol>"
    end
    lst.join
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in admin_user
    session[:admin_user_id] = admin_user.id
  end

  def log_out
    session.delete :admin_user_id
  end

  def current_admin_user
    return nil if session[:admin_user_id].blank?
    @current_admin_user ||= AdminUser.find(session[:admin_user_id])
  end
end

app/views/admin/orders/_form.html.erb
<%= form_for(order, method: 'PUT', :url => {:controller => 'admin/orders', action: action_type}) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :status, class: 'form-check-label' %>
    <%= f.select(:status, options_for_select(Order.statuses.collect {|s| [s.first.capitalize, s.first]}, order.status), {}, {class: "form-control"} ) %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<div class="row">
  <div class="col-md-5">
    <%= render 'form', order: @order, action_type: "update" %>
  </div>
</div>

<%= link_to 'Show', admin_order_path(@order) %> |
<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag(admin_orders_path, method: 'get') do %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Status</label>
        <div class="col-sm-10"><%= select_tag('search[status]', options_for_select(Order.statuses.collect {|s| [s.first.capitalize, s.first]}, params['search'].try(:[], 'status')), include_blank: true, class: 'form-control') %></div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Email</label>
        <div class="col-sm-10"><%= text_field_tag 'search[email]', params['search'].try(:[], 'email'), class: 'form-control' %></div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="actions">
        <%= submit_tag 'Search', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>
<br>
<%= paginate @orders, window: 2 %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Status</th>
      <th>Created at</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.user_email %></td>
        <td><%= order.status %></td>
        <td><%= order.created_at %></td>
        <td><%= link_to 'Show', admin_order_path(order) %></td>
        <td><%= link_to 'Edit', edit_admin_order_path(order) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @orders, window: 2 %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @order.user_email %>
  <br>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<%= link_to 'Edit', edit_admin_order_path(@order) %> |
<%= link_to 'Back', admin_orders_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="sb-nav-fixed">
    <%= render 'layouts/shared/header' %>
    <div id="layoutSidenav">
      <div id="layoutSidenav_nav">
        <%= render 'layouts/shared/navbar' %>
      </div>
      <div id="layoutSidenav_content">
        <main>
          <div class="container-fluid">
            <%= generate_breadcrum(@bcrum_title, @bcrum_detail).html_safe %>
            <%= yield %>
          </div>
        </main>
        <%= render 'layouts/shared/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="py-4 bg-light mt-auto">
  <div class="container-fluid">
    <div class="d-flex align-items-center justify-content-between small">
      <div class="text-muted">Copyright &copy; Order System 2021</div>
      <div>
        <!-- <a href="#">Privacy Policy</a>
        &middot;
        <a href="#">Terms &amp; Conditions</a> -->
      </div>
    </div>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <%= link_to("Order System", admin_root_path , class: 'navbar-brand') %>
  <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
  <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0"></div>
  <ul class="navbar-nav ml-auto ml-md-0">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <!-- <a class="dropdown-item" href="#">Settings</a>
        <a class="dropdown-item" href="#">Activity Log</a>
        <div class="dropdown-divider"></div>-->
        <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/shared/_navbar.html.erb
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
  <div class="sb-sidenav-menu">
    <div class="nav">
      <div class="sb-sidenav-menu-heading">Core</div>
      <a class="nav-link" href="<%= admin_root_path %>">
        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
        Order
      </a>
    </div>
  </div>
  <div class="sb-sidenav-footer">
    <div class="small">Logged in as:</div>
    <%= current_admin_user.email %>
  </div>
</nav>